name: Full Flutter CI

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: flutter-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: false

  flutter-analyze:
    name: flutter analyze / flutter test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: "stable"
          flutter-version: "3.24.5" # keep in sync with FLUTTER_VERSION in flutter-build.yml

      - name: flutter pub get
        working-directory: flutter
        run: flutter pub get

      - name: flutter analyze
        working-directory: flutter
        run: flutter analyze

      - name: flutter test
        working-directory: flutter
        run: flutter test
